elems:

  - src: elems/(vimperatorrc)$
    dst: ~/.<1>
    only:
      features:
        - vimperator

  - src: elems/vimperator/(.+)$
    dst: ~/.vimperator/<1>
    only:
      features:
        - vimperator_dir

# vim: set filetype=eruby.yaml :
